function B = B1(in1,in2)
%B1
%    B = B1(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 23.2.
%    15-May-2025 16:00:39

u1 = in2(1,:);
u2 = in2(2,:);
x1 = in1(1,:);
x6 = in1(6,:);
t2 = u2+x6;
t5 = 1.0./x1;
t3 = cos(t2);
t4 = sin(t2);
B = reshape([-3.088993914681988e-4,0.0,0.0,t3.*t5,-t4.*t5,0.0,t5.*sin(u2).*(-9.372254222395782e-2),0.0,0.0,0.0,-t4.*t5.*u1,-t3.*t5.*u1,0.0,t5.*u1.*cos(u2).*(-9.372254222395782e-2)],[7,2]);
end
